// <auto-generated />
using System;
using DogApp.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogApp.DAL.Migrations
{
    [DbContext(typeof(DogAppDbContext))]
    [Migration("20231018143843_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogApp.DAL.Entities.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<short>("TailLength")
                        .HasColumnType("smallint")
                        .HasColumnName("tail_length");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("dogs", t =>
                        {
                            t.HasCheckConstraint("CK_Dogs_TailLength_GreaterThanZero", "[tail_length] > 0");

                            t.HasCheckConstraint("CK_Dogs_Weight_GreaterThanZero", "[weight] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("adb36a6d-4d2a-4a6e-9c9e-df460915f5b1"),
                            Color = "red & amber",
                            Name = "Neo",
                            TailLength = (short)22,
                            Weight = (short)32
                        },
                        new
                        {
                            Id = new Guid("a2d8578f-02d4-4c3f-80b9-6c9763767dcf"),
                            Color = "black & white",
                            Name = "Jessy",
                            TailLength = (short)7,
                            Weight = (short)14
                        },
                        new
                        {
                            Id = new Guid("639c89ce-c711-4aad-9b80-bf7d9afec10b"),
                            Color = "black",
                            Name = "IceCube",
                            TailLength = (short)22,
                            Weight = (short)38
                        },
                        new
                        {
                            Id = new Guid("841146ef-4fc7-4d72-b8eb-9e72be4f5a25"),
                            Color = "black",
                            Name = "Snoop",
                            TailLength = (short)22,
                            Weight = (short)38
                        },
                        new
                        {
                            Id = new Guid("e6bc34c9-40ef-45b7-b1ff-9ba9ecbd1f34"),
                            Color = "white",
                            Name = "Eminem",
                            TailLength = (short)14,
                            Weight = (short)13
                        },
                        new
                        {
                            Id = new Guid("9315a1af-1df0-4fc4-ab84-03388d14b2a2"),
                            Color = "brown",
                            Name = "50Cent",
                            TailLength = (short)14,
                            Weight = (short)44
                        },
                        new
                        {
                            Id = new Guid("4107f4c3-0f2a-4e41-869f-5d1884ac2fc5"),
                            Color = "orange",
                            Name = "Babangida",
                            TailLength = (short)5,
                            Weight = (short)12
                        },
                        new
                        {
                            Id = new Guid("b75c7548-aaed-4a0a-a614-9eddb7d1bc2b"),
                            Color = "black",
                            Name = "Phife Dawg",
                            TailLength = (short)4,
                            Weight = (short)9
                        },
                        new
                        {
                            Id = new Guid("a1c9b960-0dfa-4d6b-825a-e7f9cc464ed9"),
                            Color = "black & brown",
                            Name = "Kanye West",
                            TailLength = (short)10,
                            Weight = (short)30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
